/* Extra quotes for LoFiDashboard.html - keep this file in the same folder as the widget.
   Each entry is { t: "quote", a: "author" }. Add, edit or delete lines freely. */
window.EXTRA_QUOTES = [
    { t: "Cuộc sống quá ngắn, và quá đẹp. Đừng quá quan trọng công việc. Hãy tận hưởng cuộc đời", a: "Jack Ma" },
    { t: "Tôi yêu cuộc sống. Đôi lúc tôi đau khổ tới dữ dội, sâu sắc, tuyệt vọng, lấp đầy bởi muộn phiền; nhưng qua tất cả, tôi vẫn biết khá chắc chắn rằng được sống là một điều tuyệt diệu", a: "Agatha Christie" },
    { t: "Sống vô tư nhưng không khinh suất; vui tươi nhưng không ầm ĩ; can đảm nhưng không liều lĩnh; tin tưởng và vui vẻ cam chịu nhưng không theo thuyết định mệnh - đó là nghệ thuật sống", a: "Khuyết danh" },
    { t: "Cuộc đời này đáng sống, ta có thể nói như vậy, bởi nó là điều mà chúng ta tạo nên", a: "William James" },
    { t: "Cuộc sống chia làm ba thì - đã từng, hiện đang, và sẽ là. Chúng ta hãy học từ quá khứ để hưởng thành quả nhờ và từ hiện tại, để sống tốt đẹp hơn trong tương lai", a: "William Wordsworth" },
    { t: "Cuộc sống là một món quà, và nó cho chúng ta đặc ân, cơ hội, và trách nhiệm trao tặng lại điều gì đó bằng cách trở nên lớn lao hơn", a: "Khuyết danh" },
    { t: "Để cuộc sống tươi đẹp hơn, hãy dậy thật sớm mỗi ngày, để tận hưởng ánh nắng chan hòa của buổi sáng mai", a: "Khuyết danh" },
    { t: "Cuộc đời là một hỗn hợp kỳ lạ. Chúng ta phải đón nhận nó như nó vốn có, cố gắng thấu hiểu nó, và rồi làm nó tốt đẹp hơn", a: "Rabindranath Tagore" },
    { t: "Cho nhiều hơn nhận thì sẽ được nhận nhiều hơn cho", a: "Khuyết danh" },
    { t: "Không có gì là không thể. Bởi thế giới này chính đã nó nói rằng 'Tôi có thể' mà", a: "Audrey Hepburn" },
    { t: "Hãy tự tin rằng bạn có thể làm được, như vậy là bạn đã vượt qua một nửa con đường rồi đấy", a: "Theodore Roosevelt" },
    { t: "Bạn đấm mạnh thế nào không thành vấn đề bằng việc bạn bị đánh mạnh thế nào và vẫn tiếp tục tiến về phía trước", a: "Rocky Balboa" },
    { t: "Trở thành phiên bản hạng nhất của chính mình thì tốt hơn nhiều lần so với việc trở thành bản sao của ai đó.", a: "Judy Garland" },
    { t: "Tôi đã thất bại thật nhiều thật nhiều lần trong cuộc đời mình. Và đó cũng là động lực để cho tôi trở nên thành công như bây giờ.", a: "Michael Jordan" },
    { t: "Lạc quan là niềm tin dẫn tới thành tựu. Bạn chẳng thể làm được điều gì mà thiếu đi hy vọng và sự tự tin", a: "Helen Keller" },
    { t: "Bốn điều mà thế hệ trẻ nên suy ngẫm: Thất bại là gì: Bỏ cuộc là thất bại lớn nhất. Kiên cường là gì: Một khi bạn đã kinh qua gian khó, uất hận và thất vọng, chỉ khi đó bạn mới hiểu được kiên cường là gì. Nghĩa vụ của bạn là: Siêng năng hơn, chăm chỉ hơn, và tham vọng hơn người khác. Chỉ kẻ ngu mới dùng miệng để nói. Người thông minh dùng trí óc, và người sáng suốt dùng trái tim", a: "Jack Ma" },
    { t: "Như lạc đà không hề uể oải dù vất vả, nóng bức, đói, khát trên sa mạc đầy cát; sức chịu đựng ngoan cường sẽ giúp con người vượt qua mọi hiểm họa", a: "Akhenaton" },
    { t: "Để trở thành một ngôi sao, bạn phải tự tỏa ánh sáng của riêng mình, đi theo con đường của riêng mình, và đừng lo lắng về bóng tối, bởi đó là khi sao sáng nhất", a: "Khuyết danh" },
    { t: "Bạn không trưởng thành, chẳng ai trưởng thành thay bạn được. Bạn không kiên cường, chẳng ai kiên cường thay bạn được", a: "Khuyết danh" },
    { t: "Cuộc đời không bao giờ đưa ai vào ngõ cụt. Chỉ có con người tự đưa nhau vào đường cùng", a: "Khuyết danh" },
    { t: "Trong cuộc sống, giai đoạn khó nhất không phải là không ai hiểu bạn, mà là bạn không hiểu chính mình", a: "Khuyết danh" },
    { t: "Những phiền não trong cuộc đời được gói gọn trong 12 chữ: không buông được, nghĩ không thông, nhìn không thấu, quên không nổi", a: "Khuyết danh" },
    { t: "Cuộc sống là do ta tạo nên, vẫn luôn như thế, mãi mãi như thế", a: "Grandma Moses" },
    { t: "Cuộc sống không phải là đi tìm bản thân mình. Cuộc sống là tạo ra bản thân mình", a: "George Bernard Shaw" },
    { t: "Cái ngày đen tối nhất rồi cũng sẽ trôi qua nếu bạn sống tới ngày mai", a: "William Cowper" },
    { t: "Cuộc sống không phải là để chờ đợi cơn bão đi qua, cuộc sống là để học được cách khiêu vũ trong mưa", a: "Vivian Greene" },
    { t: "Khi cuộc đời cho bạn cả trăm lý do để khóc, hãy cho đời thấy bạn có cả ngàn lý do để cười", a: "Khuyết danh" },
    { t: "Khi bạn nghiêm khắc với bản thân, cuộc sống tự nhiên sẽ dễ dàng. Khi bạn dễ dàng với bản thân, cuộc sống tự nhiên sẽ khó khăn", a: "Zig Ziglar" },
    { t: "Cuộc sống cũng giống như tấm chăn ngắn. Bạn kéo lên, ắt hẳn ngón chân sẽ lạnh, bạn kéo xuống và bờ vai run rẩy; nhưng những người vui vẻ xoay xở cuộn mình lại và trải qua một đêm thoải mái", a: "Marion Howard" },
    { t: "Sống là điều hiếm có nhất trên thế giới này, phần lớn mọi người chỉ tồn tại, đó là tất cả", a: "Oscar Wilde" },
    { t: "Bạn có sức mạnh lớn hơn những gì mà bạn nghĩ đấy. Và khi bạn tự tin là chính mình, bạn sẽ trở nên xinh đẹp hơn rất nhiều", a: "Melissa Etheridge" },
    { t: "Một cuộc sống hạnh phúc được tạo nên từ những thứ nhỏ bé: luôn sống với bản thân mình, theo cách mà bạn suy nghĩ", a: "Marcus Aurelius" },
    { t: "Bạn chỉ sống một lần duy nhất, nhưng nếu bạn làm đúng thì một lần là đủ", a: "Mae West" },
    { t: "Chỉ có duy nhất 2 cách để bạn sống cuộc đời của mình. Một là sống như thể không gì là phép màu cả. Điều còn lại là sống như thể phép màu là tất cả mọi thứ", a: "Albert Einstein" },
    { t: "Người mà bạn nên cố gắng để trở nên tốt đẹp hơn chính là bạn của ngày hôm qua", a: "Khuyết danh" },
    { t: "Mục đích chính của chúng ta trong cuộc sống này là giúp đỡ người khác. Và nếu bạn không thể giúp họ, ít nhất đừng làm họ bị thương", a: "Đức Đạt Lai Lạt Ma XIV" },
    { t: "Bắt đầu mỗi ngày với một suy nghĩ tích cực và một trái tim biết ơn", a: "Roy T. Bennett" },
    { t: "Hãy cười lên và cả thế giới sẽ cười cùng bạn, nếu khóc, bạn sẽ phải chỉ khóc một mình", a: "Khuyết danh" },
    { t: "Cảm ơn đời mỗi sớm mai thức dậy, ta có thêm một ngày mới để yêu thương", a: "Khuyết danh" },
    { t: "Chúng ta không thể giúp đỡ tất cả mọi người được, nhưng tất cả mọi người có thể cùng nhau giúp đỡ một người", a: "Ronald Reagan" },
    { t: "Hãy thử trở thành tia hi vọng cho một người nào đó đang cảm thấy tuyệt vọng", a: "Maya Angelou" },
    { t: "Hãy tự trồng vườn và trang trí cho tâm hồn bạn, thay vì chờ đợi ai đó mang hoa đến cho bạn", a: "Jose Luis Borges" },
    { t: "Dù cho bản tin thời tiết có dự báo điều gì đi nữa, thì ta hãy cứ sống vui vẻ như thể mùa xuân đã đến rồi", a: "Lilly Pulitzer" },
    { t: "Gia đình là một cái tên, một ngôn từ mạnh mẽ; mạnh hơn lời của những pháp sư hay tiếng đáp của các linh hồn; đó là lời nguyện cầu hùng mạnh nhất", a: "Charles Dickens" },
    { t: "Khi bạn nhìn lại cuộc đời mình, những niềm hạnh phúc nhất chính là những niềm hạnh phúc gia đình", a: "Joyce Brothers" },
    { t: "Người ta càng làm nhiều, thấy nhiều và cảm nhận nhiều, người ta càng có thể làm được nhiều, và càng biết đánh giá chân thực về những điều cơ bản như gia đình, tình yêu và thấu hiểu sự đồng hành", a: "Amelia Earhart" },
    { t: "Ở điểm cuối của cuộc đời, bạn sẽ không bao giờ nuối tiếc chuyện không vượt qua thêm một bài thi, chiến thắng thêm một tranh chấp, hay hoàn thành thêm một việc kinh doanh. Bạn sẽ nuối tiếc đã không sử dụng thời gian để ở bên cạnh vợ chồng, bạn bè, con cái, hay cha mẹ mình", a: "Barbara Bush" },
    { t: "Tôi có nơi ẩn náu tuyệt vời, đó là gia đình. Tôi có mối quan hệ tuyệt vời với anh chị em của tôi; điều này khiến tôi cảm thấy mình luôn biết mình thuộc về nơi đâu", a: "Jose Carreras" },
    { t: "Hạnh phúc là cảm thấy yên bình, ở bên những người ta yêu thương, cảm thấy thoải mái... nhưng trên hết, đó là có được những người ta yêu thương", a: "Johnny Cash" },
    { t: "Trong khi từ 9:00 đến 5:00 và điều xảy ra trong công việc rất quan trọng... điều diễn ra từ 5:00 đến 9:00, trong khi bạn không làm việc, chắc chắn còn quan trọng hơn", a: "Zig Ziglar" },
    { t: "Gia đình là gì? Đó là tình mến sợ cha, tình yêu mến mẹ, kính trọng thán phục nhân đức của cả cha lẫn mẹ, bỏ qua lỗi lầm, ghi nhớ công ơn, thông cảm nỗi đau khổ, cảm kích sự hy sinh của cha mẹ", a: "" },
    { t: "Tình thân mới là thứ tình cảm đáng tin cậy nhất trên thế giới này, cho dù bạn có đáng ghét tới đâu, người duy nhất không vứt bỏ bạn chính là người nhà bạn. Họ dang rộng vòng tay, mãi mãi là cảng tránh gió của chúng ta", a: "" },
    { t: "Thời gian dành cho gia đình không phải vấn đề có tiện hay không. Đó là vấn đề của sự ưu tiên", a: "" },
    { t: "Đừng đuổi theo quyền lực mà đánh mất đạo đức, cũng như trí tuệ đem đến cho bạn hạnh phúc chứ không phải là tiền bạc và vật chất", a: "Bob Marley" },
    { t: "Khi chúng ta làm điều mình đam mê, tiền bạc sẽ tự tìm đến, các cánh cửa khác sẽ mở ra. Chúng ta cảm thấy bản thân trở nên hữu ích và công việc sẽ như một trò chơi vậy.", a: "Julia Cameron" },
    { t: "Bạn có thể trẻ mà không có tiền nhưng bạn không thể già mà thiếu nó đâu.", a: "Tennessee Williams" },
    { t: "Đừng có nằm ườn trên giường nữa, trừ phi bạn nằm trên đó mà vẫn làm ra tiền.", a: "George Burns" },
    { t: "Tiền bạc cũng như đàn bà: muốn giữ nó thì phải săn sóc nó, bằng không nó đi tạo hạnh phúc cho người khác", a: "E. Bourdet" },
    { t: "Giá trị của bạn ở trong con mắt xã hội, không phải nằm ở số tiền bạn có, mà ở số tiền bạn tiêu", a: "" },
    { t: "Có tiền mua tiên cũng được, trừ hạnh phúc", a: "S. Guitơri" },
    { t: "Trên đời có ba thứ nguy hiểm nhất: Rượu ngon làm ta mất trí, tiền bạc nhiều làm ta bất chính, vợ đẹp làm ta đau khổ nhiều. Vì: rượu ngon khiến ta thích uống; tiền nhiều thường làm mờ át lương tri; vợ đẹp thường hay phản bội. Vì thế tốt nhất là mất cả ba.", a: "J.P.Sartre" },
    { t: "Tiền bạc có thể nhen nhóm, nhưng nó không thể tự mình cháy, và cháy rất lâu", a: "Igor Stravinsky" },
    { t: "Tiền là phương tiện của những người thông minh – Tiền là mục tiêu của những kẻ ngu ngốc", a: "" },
    { t: "Hãy tin rằng đời đáng sống, và niềm tin của bạn sẽ giúp thiết lập sự thật đó", a: "William James" },
    { t: "Cuộc sống là một chuỗi bài học mà bạn cần phải sống mới hiểu được", a: "Helen Keller" },
    { t: "Chúng ta sinh ra đã khóc, sống để phàn nàn và chết trong thất vọng", a: "Thomas Fuller" },
    { t: "Cuộc đời là bi kịch khi quay gần, nhưng là hài kịch khi quay xa", a: "Charlie Chaplin" },
    { t: "Nỗi sợ cái chết đến từ nỗi sợ cuộc sống. Người sống được hết mình luôn sẵn sàng chết bất cứ lúc nào", a: "Mark Twain" },
    { t: "Nếu cuộc đời có thể đoán trước, nó sẽ không còn là cuộc đời, và cũng không còn hương vị nữa", a: "Eleanor Roosevelt" },
    { t: "Người không chinh phục nỗi sợ hãi hàng ngày vẫn chưa học được bí mật của cuộc sống", a: "Ralph Waldo Emerson" },
    { t: "Hãy sống mà không giả tạo, yêu mà không phụ thuộc, lắng nghe mà không phòng thủ, nói mà không xúc phạm", a: "Drake" },
    { t: "Tốt nhất hãy vươn lên trong cuộc sống, cũng như rời khỏi yến hội, không khát, cũng không say", a: "Aristotle" },
    { t: "Đời sống, Đời chết. Đời cười, Đời khóc. Đời thử và Đời bỏ cuộc. Nhưng Đời trông khác biệt trong mắt của mỗi người", a: "" },
    { t: "Cuộc sống không công bằng; hãy quen với điều đó đi", a: "Bill Gates" },
    { t: "Đôi khi cuộc đời sẽ ném gạch vào đầu bạn. Đừng đánh mất niềm tin", a: "Steve Jobs" },
    { t: "Thước đo của cuộc đời không phải thời gian, mà là cống hiến", a: "Peter Marshall" },
    { t: "Quan trọng không phải là sống lâu như thế nào, mà là sống sâu như thế nào", a: "Ralph Waldo Emerson" },
    { t: "Chúng ta không có cơ hội làm quá nhiều điều, và mỗi thứ chúng ta làm đều phải thật sự tuyệt vời. Bởi vì đây là cuộc đời của chúng ta. Cuộc đời ngắn ngủi lắm, và rồi bạn chết, bạn biết chứ? Và chúng ta đều được lựa chọn để làm điều này với cuộc đời mình. Vì vậy điều ta làm nên thật tốt. Nên đáng giá", a: "Steve Jobs" },
    { t: "Có những người chết ở tuổi 25 và chỉ đến 75 tuổi mới được chôn", a: "Benjamin Franklin" },
    { t: "Khi sinh ra, ta cất tiếng khóc bởi ta đã bước vào sân khấu vĩ đại của những kẻ dại khờ", a: "William Shakespeare" },
    { t: "Phòng ốc thế nào không quan trọng, quan trọng là cuộc đời bạn sống trong đó", a: "Coco Chanel" },
    { t: "Bạn phải cứu bất cứ phần nào của cuộc đời mình; bạn không thể đánh mất cả cuộc đời chỉ vì đã mất một phần", a: "Henry James" },
    { t: "Cuộc sống không phải lúc nào cũng giống như bạn muốn, nhưng nó luôn luôn diễn ra theo cách nó phải thế", a: "Katrina Mayer" },
    { t: "Trò chơi cuộc sống rất hay, dù tất cả trong cuộc sống đều có thể đau đớn, và dù tất cả mọi cuộc đời đến cuối đường đều sẽ thua cuộc", a: "Jack London" },
    { t: "Cuộc sống có hai bi kịch. Một là không lấy được điều mà mình khát khao, và hai là lấy được nó", a: "Socrates" },
    { t: "Tôi đã biết niềm vui và nỗi đau của tình bạn. Tôi đã phụng sự và được phụng sự. Tôi đã tạo ra vài kẻ thù mà tôi chẳng hề hối tiếc việc đó. Tôi đã yêu không ích kỷ, và tôi đã vuốt ve thù hận với cái kẹp nóng đỏ của Địa ngục. Đó chính là sống", a: "Zora Neale Hurston" },
    { t: "Bạn làm điều gì đầu tiên khi học bơi? Bạn phạm lỗi, không phải sao? Và chuyện gì xảy ra? Bạn phạm các lỗi khác, và khi bạn phạm xong tất cả các lỗi mình có thể phạm mà không chết đuối - và một vài lỗi còn phạm đi phạm lại - bạn phát hiện ra điều gì? Rằng mình có thể bơi rồi? Chà - cuộc đời cũng giống như học bơi! Đừng sợ phạm lỗi, vì không còn cách nào khác để học sống!", a: "Alfred Adler" },
    { t: "Cuộc sống ném vào bạn những chuyện bạn chẳng thể kiểm soát, nhưng bạn vẫn có thể chọn cách bạn sẽ vượt qua chúng", a: "Celine Dion" },
    { t: "Cuộc sống không có sự cân bằng có thể làm hỏng những mối quan hệ của bạn. Cuộc sống không có sự cân bằng có thể làm sức khỏe của bạn tồi tệ hơn. Cuộc sống không có sự cân bằng có thể làm tổn thương tâm hồn bạn. Cuộc sống không có sự cân bằng có thể làm bạn đánh mất sự giàu sang và hạnh phúc. Vậy nên hãy tìm những thứ truyền động lực cho bạn trong tất cả mọi mặt của cuộc sống. Thành công của bạn phụ thuộc vào điều đó", a: "Jim Rohn" },
    { t: "Sống là đau khổ, sống sót là tìm được ý nghĩa trong đau khổ", a: "Friedrich Nietzsche" },
    { t: "Cuộc đời như màn kịch, mỗi người đều đang đeo mặt nạ để diễn kịch, khi không cần cái mặt nạ này nữa, lập tức vứt đi, rồi lại thay một chiêc mặt nạ khác để tiếp tục diễn vở kịch cuộc đời. - Mẹ chồng ăn thịt cả nhà nàng dâu", a: "Kỷ Đạt" },
    { t: "Cuộc sống không phải luôn luôn là vấn đề bạn có bao nhiêu bài tốt, mà đôi khi là việc bạn chơi quân bài xấu tốt thế nào", a: "Jack London" },
    { t: "Ác quỷ đã đặt hình phạt lên tất cả những thứ chúng ta yêu thích trong đời. Hoặc chúng ta kém sức khỏe, hoặc chúng ta khốn khổ về tinh thần, hoặc chúng ta trở nên béo", a: "Albert Einstein" },
    { t: "Giữa tình yêu sâu sắc cuộc đời và bóng tối trong trái tim là nỗi u uẩn trong suốt nhưng cũng lạnh buốt như sương đêm. Cuộc sống vẫn tiếp diễn, thản nhiên như thế, vô tình như thế…", a: "Giang Sơn" },
    { t: "Với phân tích cuối cùng, tình yêu là cuộc sống. Tình yêu không bao giờ thất bại và cuộc sống không bao giờ thất bại chừng nào còn có tình yêu", a: "Henry Drummond" },
    { t: "Cuộc sống và tình yêu đều vô cùng quý giá khi chúng đang nở rộ", a: "Louisa May Alcott" },
    { t: "Cuộc đời này rất giống một nụ hôn, nó có thể khiến bạn hạnh phúc, cũng có thể làm bạn vỡ mộng, nó có thể khiến bạn nhận ra mình yêu, hay nhận ra mình hoàn toàn không yêu. Nó chứa đựng những bí mật mà bạn chỉ khám phá được sau khi đã hoàn thành", a: "Phạm Lữ Ân" },
    { t: "Cuộc đời này, ngắn thì ngắn mà tình cảm lại quá dài, tình yêu khiến cho vạn vật tươi đẹp diễm lệ, mà cũng khiến cho sự biệt ly đau đớn hơn hết thảy mọi thứ trên đời", a: "Sói Xám Mọc Cánh" },
    { t: "Cuộc sống và tình yêu tiếp tục trôi, hãy để nhạc vang lên", a: "Johnny Cash" },
    { t: "Đừng che dấu yêu thương. Hãy nói cho mọi người xung quanh bạn biết bạn yêu thương họ rất nhiều. Hãy nói những câu nói đẹp và ngọt ngào nhất khi bạn có thể nói. Đừng giữ lại những lời nói yêu thương qua bên kia thế giới", a: "" },
    { t: "Hãy phá vỡ luật lệ, tha thứ nhanh chóng, hôn chậm rãi, yêu thực lòng, cười không kiềm chế", a: "" },
    { t: "Với thế giới, bạn có thể chỉ là một người, nhưng với một người, bạn có thể là cả thế giới", a: "" },
    { t: "Người nói yêu bạn, chưa chắc có thể đợi được bạn. Nhưng người đợi được bạn, chắc chắn sẽ rất yêu bạn…", a: "" },
    { t: "Bình yên đến từ bên trong. Đừng tìm kiếm nó bên ngoài", a: "" },
    { t: "Một người nếu tự đáy lòng không thể tha thứ cho kẻ khác, thì lòng họ sẽ không bao giờ được thanh thản", a: "" },
    { t: "Hận thù người khác là một mất mát lớn nhất đối với chính mình", a: "" },
    { t: "Thế giới vốn không thuộc về bạn, vì thế bạn không cần vứt bỏ, cái cần vứt bỏ chính là những tánh cố chấp. Vạn vật đều cung ứng cho ta, nhưng không thuộc về ta", a: "" },
    { t: "Người che đậy khuyết điểm của mình bằng thủ đoạn tổn thương người khác là kẻ đê tiện", a: "" },
    { t: "Người không biết yêu mình thì không thể yêu được người khác", a: "" },
    { t: "Khi bạn vui, phải nghĩ rằng niềm vui này không phải là vĩnh hằng. Khi bạn đau khổ, bạn hãy suy nghĩ rằng nỗi đau này cũng không trường tồn", a: "" },
    { t: "Nói năng đừng có tánh châm chọc, đừng gây thương tổn, đừng khoe tài cán của mình, đừng phô điều xấu của người, tự nhiên sẽ hóa địch thành bạn", a: "" },
    { t: "Muốn hiểu một người, chỉ cần xem mục đích đến và xuất phát điểm của họ có giống nhau hay không thì có thể biết được họ có thật lòng không", a: "" },
    { t: "Đời người có bao nhiêu toan tính thì có bấy nhiêu đau khổ. Có bao nhiêu khoan dung thì có bấy nhiêu niềm vui", a: "" },
    { t: "Khi người phụ nữ tái hôn, đó là bởi nàng căm ghét ông chồng đầu tiên. Khi người đàn ông tái hôn, đó là bởi anh ta mê mẩn người vợ đầu tiên. Phụ nữ thử xem vận may của mình; đàn ông mạo hiểm vận may của mình", a: "Oscar Wilde" },
    { t: "Xiềng xích không trói được cuộc hôn nhân không tan vỡ. Những sợi chỉ, hàng trăm sợi chỉ nhỏ bé mới là thứ nối con người lại bên nhau qua năm tháng", a: "Simone Signoret" },
    { t: "Gần gũi mà xa cách, lên tiếng mà không được lắng nghe, yêu thương mà không được yêu, đó là hiện thực đau đớn của một mối quan hệ đang chết dần", a: "Steve Maraboli" },
    { t: "Ly dị chỉ bởi vì bạn không yêu đối phương cũng ngu xuẩn gần như là kết hôn chỉ vì bạn yêu đối phương", a: "Zsa Zsa Gabor" },
    { t: "Ở đời, chẳng ai có trách nhiệm phải yêu thương ai hết. Người luôn yêu em rồi cũng sẽ rời bỏ em khi nhẫn nại cùng tự tôn đều mất đi. Người ta đâu chỉ sống để đơn phương phía sau, mãi nhìn về một hướng. Em rồi sẽ hiểu, từ bỏ đôi khi đồng nghĩa với thở dài…thanh thản buông tay một người để tìm kiếm cả bầu trời xanh… Vì ai lại bên ai mãi được đâu…", a: "Yusakumi Kudo" },
    { t: "Đàn ông kết hôn vì họ mệt mỏi. Phụ nữ kết hôn vì họ tò mò. Cả hai đều thất vọng", a: "Oscar Wilde" },
    { t: "Một vài trái tim được hàn gắn, một vài trái tim nát tan, mặc dù chẳng bao giờ có ai muốn vậy, bởi tình yêu luôn được thề thốt đầu bạc răng long. Tôi đã khóc, và cầu nguyện, và van xin, chỉ mong tình yêu bền vững. Hy vọng là tất cả những gì tôi cần, và đau đớn là tất cả những gì tôi tìm thấy", a: "" },
    { t: "Anh em cãi nhau cả ngày không mất; vợ chồng cãi nhau một lúc thành người dưng", a: "" },
    { t: "Hôn nhân là sự vun đắp của tình yêu, nỗi đau, sự nhẫn nhịn, sự bức bối và sau cùng là hạnh phúc", a: "" },
    { t: "Tình yêu giống như hai người cùng kéo một sợi dây chun. Nếu một người buông, người còn níu giữ sẽ đau đớn", a: "" },
    { t: "Sự giả dối có vô vàn biến thể, nhưng sự thật chỉ có một thể tồn tại duy nhất", a: "Jean Jacques Rousseau" },
    { t: "Dối trá và lừa lọc là hành động của kẻ ngu xuẩn không có đủ trí óc để trung thực", a: "Benjamin Franklin" },
    { t: "Sự thật, giống như ánh sáng, làm người ta chói mắt. Sự giả dối thì ngược lại, là ánh chiều hôm tươi đẹp bao trùm lên mọi vật", a: "Albert Camus" },
    { t: "Một vài người nghĩ rằng có thể giấu đi sự thật với một chút bao che và tô điểm. Nhưng khi thời gian trôi đi, sự thật sẽ lộ ra, và điều giả dối sẽ phai mờ", a: "Ismail Haniyeh" },
    { t: "Thời gian trôi đi, và từng chút từng chút, mọi điều mà ta nói bằng lời dối trá trở thành sự thật", a: "Marcel Proust" },
    { t: "Lời dối trá không nằm ở ngôn từ quanh co, mà ở trong mong muốn và ý định lừa gạt và làm tổn thương đối phương qua lời nói giả tạo", a: "Jonathan Swift" },
    { t: "Trong tình yêu, tốt nhất là đừng giả dối. Nếu cảm thấy không vui vẻ, không hạnh phúc thì bỏ nó đi", a: "" },
    { t: "Nghèo chẳng nên nói dối, giàu chẳng nên cậy mình", a: "Thái Công" },
    { t: "Sự dối trá bay, và sự thật lê lết đằng sau, nên khi con người tỉnh ngộ, đã quá muộn; trò đùa chơi đã kết thúc, và câu chuyện đã để lại ảnh hưởng: giống như người nghĩ ra được lời đối đáp hay khi mà chủ đề đã đổi, hoặc đối phương đã rời đi; hay giống như người bác sĩ tìm ra được liều thuốc chắc chắn chữa được sau khi bệnh nhân đã chết", a: "Jonathan Swift" },
    { t: "Có hai cách để bị lừa. Một là tin vào điều không đúng; và một là không chịu tin vào điều đúng", a: "Soren Kierkegaard" },
    { t: "Hãy cẩn thận môi trường bạn chọn vì nó sẽ định hình bạn; hãy cẩn thận những người bạn mà bạn lựa chọn bởi bạn sẽ trở nên như họ", a: "W. Clement Stone" },
    { t: "Nếu bạn yêu hai người cùng một lúc, thì tôi khuyên bạn hãy chọn người thứ hai. Nếu người thứ nhất đủ hoàn hảo thì bạn sẽ không để ý đến người thứ hai đâu. Tin tôi đi!", a: "" },
    { t: "Bạn luôn luôn làm việc mình muốn làm. Điều này đúng với mọi hành động. Bạn có thể nói bạn phải làm, hoặc bạn bị buộc phải làm, nhưng thực ra, dù bạn làm gì cũng là do bạn chọn lựa. Chỉ mình bạn có quyền năng lựa chọn cho bản thân mình", a: "W. Clement Stone" },
    { t: "Cuộc sống của bạn là kết quả của những lựa chọn bạn lập. Nếu bạn không thích cuộc sống của mình, đã đến lúc lập những lựa chọn tốt hơn", a: "Katrina Mayer" },
    { t: "Bạn nên cẩn thận quan sát con đường mà trái tim dẫn bạn đến, rồi lựa chọn con đường ấy bằng tất cả sức mạnh của mình", a: "Martin Buber" },
    { t: "Trong suốt cuộc đời bạn, bạn sẽ đối mặt với một lựa chọn. Bạn có thể chọn yêu thương hay căm hận... Tôi chọn yêu thương", a: "Johnny Cash" },
    { t: "Những lựa chọn của bạn cũng tạo nên con người bạn. Đừng lắng nghe những điều níu kéo mình lại. Thay vì thế, hãy lắng nghe những điều thúc đẩy bạn tiến lên", a: "Edwin Mamerto" },
    { t: "Lựa chọn dành cho nhân loại là giữa tự do và hạnh phúc, và đối với phần lớn nhân loại, hạnh phúc tốt đẹp hơn", a: "George Orwell" },
    { t: "Cách bạn sống mỗi ngày là một câu trong câu chuyện cuộc đời bạn. Mỗi ngày bạn lựa chọn liệu câu ấy kết thúc bằng dấu chấm, dấu hỏi, hay dấu chấm than", a: "Steve Maraboli" },
    { t: "Điều đáng sợ nhất mà một người phải đối diện không phải là thất bại hay mất mát. Mà chính là lúc tỉnh giấc mỗi buổi sáng, không mong muốn gì, không khát khao gì. Bởi vì trái tim rỗng toác. Bất mãn với cả chính bản thân mình. Khi ấy, có lẽ điều kỳ diệu là một từ ngữ quá xa xỉ và nực cười. Nhưng rồi, chúng ta cũng phải tự cứu chính mình thôi. Bạn luôn có sự lựa chọn, ngay cả khi cùng cực nhất. Là đứng lên và đi hay đứng lại rồi bị quên lãng. Quyền quyết định thuộc về bạn", a: "Phan Ý Yên" },
    { t: "Nếu không bắt đầu thì sẽ không có kết thúc. Nhưng…nếu không có kết thúc thì…cũng sẽ không có bắt đầu", a: "" },
    { t: "Một ngày đi tu thì không thể thành chính quả, nhưng một ngày ngu thì nhận biết bao nhiêu hậu quả", a: "" },
    { t: "Đằng sau người là ông thất bại là một người đàn bà xúi dại. Đằng sau người đàn bà xúi dại là một kẻ thứ ba rất lợi hại", a: "" },
    { t: "Giúp đỡ người khác khi gặp khó khăn, và họ sẽ nhớ tới bạn khi họ lại gặp khó khăn", a: "" },
    { t: "Tiền không phải tất cả nhưng sẽ thật vất vả khi không có tiền", a: "" },
    { t: "Người ta yêu nhau ngay từ cái nhìn đầu tiên, rồi sau đó lại thở dài nuối tiếc sao ngày xưa không nhìn kỹ thêm lần nữa", a: "" },
    { t: "Đằng sau sự thành công của một người đàn ông luôn có hình bóng của một người đàn bà, và đằng sau sự thất bại của một người đàn ông là một người đàn bà thật sự", a: "" },
    { t: "Cuộc đời là vở kịch dài. Ta là vai chính cả hài lẫn bi", a: "" },
    { t: "Có những thứ chỉ khi mất đi rồi, ta mới nhận ra rằng mình không còn nó nữa", a: "" },
    { t: "Khi bạn yêu đời thì bạn có thể tha thứ cho người đời rất nhiều chuyện", a: "" },
    { t: "Đừng khóc vì nó kết thúc, hãy cười vì nó đã xảy ra", a: "Dr. Seuss" },
    { t: "Hãy sống với hiện tại", a: "Anonymous" },
    { t: "Bạn tốt, sách hay và một lương tâm thanh thản: đó chính là cuộc sống lý tưởng", a: "Mark Twain" },
    { t: "Mọi điều bạn có thể tưởng tượng được đều là thật", a: "Pablo Picasso" },
    { t: "Cuộc sống không có điều khiển từ xa. Hãy tự đứng dậy và thay đổi nó", a: "" },
    { t: "Đừng bám lấy những giấc mơ mà quên mất cuộc sống hiện tại", a: "" },
    { t: "Cuộc sống luôn cho bạn một cơ hội thứ hai. Nó được gọi là ngày mai", a: "" },
    { t: "Đôi khi câu hỏi thường phức tạp thì câu trả lời sẽ rất đơn giản", a: "" },
    { t: "Chúng ta không bao giờ có thể học được để trở nên can đảm và kiên nhẫn nếu chỉ có niềm vui trên thế gian này", a: "" },
    { t: "Cuộc đời ngắn lắm, hãy cười khi bạn vẫn còn răng", a: "" }
];
